apiVersion: v1
kind: Service
metadata:
  name: wp-web
  labels:
    app: wp-web
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30180
  selector:
    app: wp-web
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-web
  labels:
    app: wp-web
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-web
        tier: frontend
    spec:
      containers:
        - image: dome/wp
          name: wordpress
          env:
            - name: WORDPRESS_DB_HOST
              value: galera-db
            - name: WORDPRESS_DB_NAME
              value: wp_web_db
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db
                  key: password
          ports:
            - containerPort: 80
              name: wp-web
          volumeMounts:
            - name: wordpress-local-storage
              mountPath: /DATA
          imagePullPolicy: Always
      volumes:
        - name: wordpress-local-storage
          persistentVolumeClaim:
            claimName: www-nfs